name: video2gif Package and Release

on:
  release:
    types: [created]

jobs:
  package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            arch: x86_64
            name: Darwin_x86_64
          - target: aarch64-apple-darwin
            arch: arm64
            name: Darwin_arm64
          - target: x86_64-unknown-linux-gnu
            arch: x86_64
            name: Linux_x86_64
          - target: aarch64-unknown-linux-gnu
            arch: arm64
            name: Linux_arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Package binary
        run: |
          tar -czvf video2gif_${{ matrix.name }}.tar.gz video2gif

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: video2gif_${{ matrix.name }}.tar.gz
          path: video2gif_${{ matrix.name }}.tar.gz

  checksum:
    needs: package
    runs-on: ubuntu-latest
    env:
      VERSIONTAG: ${{ github.event.release.tag_name }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Generate checksums
        run: |
          for file in artifacts/*.tar.gz/*.tar.gz; do
            sha256sum "$file" | awk '{gsub(/.*\//, "", $2); print $1 "  " $2}' >> video2gif_${{ env.VERSIONTAG }}_checksums.txt
          done

      - name: Upload checksum file
        uses: actions/upload-artifact@v4
        with:
          name: video2gif_${{ env.VERSIONTAG }}_checksums.txt
          path: video2gif_${{ env.VERSIONTAG }}_checksums.txt

  upload-release-assets:
    needs: [package, checksum]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Upload Release Checksums
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifacts/video2gif_${{ github.event.release.tag_name }}_checksums.txt/video2gif_${{ github.event.release.tag_name }}_checksums.txt
          asset_name: video2gif_${{ github.event.release.tag_name }}_checksums.txt
          asset_content_type: text/plain

      - name: Upload Darwin x86_64 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifacts/video2gif_Darwin_x86_64.tar.gz/video2gif_Darwin_x86_64.tar.gz
          asset_name: video2gif_Darwin_x86_64.tar.gz
          asset_content_type: application/gzip

      - name: Upload Darwin arm64 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifacts/video2gif_Darwin_arm64.tar.gz/video2gif_Darwin_arm64.tar.gz
          asset_name: video2gif_Darwin_arm64.tar.gz
          asset_content_type: application/gzip

      - name: Upload Linux x86_64 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifacts/video2gif_Linux_x86_64.tar.gz/video2gif_Linux_x86_64.tar.gz
          asset_name: video2gif_Linux_x86_64.tar.gz
          asset_content_type: application/gzip

      - name: Upload Linux arm64 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifacts/video2gif_Linux_arm64.tar.gz/video2gif_Linux_arm64.tar.gz
          asset_name: video2gif_Linux_arm64.tar.gz
          asset_content_type: application/gzip

  homebrew-tap:
    needs: [package, checksum, upload-release-assets]
    runs-on: ubuntu-latest
    env:
      VERSIONTAG: ${{ github.event.release.tag_name }}
    steps:
      - name: Checkout homebrew-tap repository
        uses: actions/checkout@v4
        with:
          repository: stenstromen/homebrew-tap
          token: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
          path: homebrew-tap

      - name: Download checksum file
        uses: actions/download-artifact@v4
        with:
          name: video2gif_${{ env.VERSIONTAG }}_checksums.txt
          path: .

      - name: Create Homebrew Formula
        run: |
          REPO_NAME="video2gif"
          REPO_URL="https://github.com/Stenstromen/${REPO_NAME}"
          FORMULA_PATH="homebrew-tap/Formula/${REPO_NAME}.rb"
          CHECKSUM_FILE="video2gif_${{ env.VERSIONTAG }}_checksums.txt"

          cat > "${FORMULA_PATH}" << EOF
          # typed: false
          # frozen_string_literal: true
          class Video2Gif < Formula
            desc "A comprehensive bash script that converts video files to optimized GIFs using ffmpeg and gifsicle"
            homepage "${REPO_URL}"
            version "${VERSIONTAG}"

            on_macos do
              if Hardware::CPU.arm?
                url "${REPO_URL}/releases/download/${VERSIONTAG}/${REPO_NAME}_Darwin_arm64.tar.gz"
                sha256 "$(grep 'video2gif_Darwin_arm64.tar.gz' $CHECKSUM_FILE | awk '{print $1}')"

                def install
                  bin.install "${REPO_NAME}"
                end
              end
              if Hardware::CPU.intel?
                url "${REPO_URL}/releases/download/${VERSIONTAG}/${REPO_NAME}_Darwin_x86_64.tar.gz"
                sha256 "$(grep 'video2gif_Darwin_x86_64.tar.gz' $CHECKSUM_FILE | awk '{print $1}')"

                def install
                  bin.install "${REPO_NAME}"
                end

              end
            end

            on_linux do
              if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
                url "${REPO_URL}/releases/download/${VERSIONTAG}/${REPO_NAME}_Linux_arm64.tar.gz"
                sha256 "$(grep 'video2gif_Linux_arm64.tar.gz' $CHECKSUM_FILE | awk '{print $1}')"

                def install
                  bin.install "${REPO_NAME}"
                end
              end
              if Hardware::CPU.intel?
                url "${REPO_URL}/releases/download/${VERSIONTAG}/${REPO_NAME}_Linux_x86_64.tar.gz"
                sha256 "$(grep 'video2gif_Linux_x86_64.tar.gz' $CHECKSUM_FILE | awk '{print $1}')"

                def install
                  bin.install "${REPO_NAME}"
                end

              end
            end
          end
          EOF

      - name: Commit and Push Homebrew Formula
        run: |
          cd homebrew-tap
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add Formula/video2gif.rb
          git commit -m "Update video2gif formula for version $VERSIONTAG"
          git push
